{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snapshot-validation-webhook.serviceAccountName" . }}
  labels:
    {{- include "snapshot-validation-webhook.labels" . | nindent 4 }}
{{- end }}
