apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "snapshot-validation-webhook.fullname" . }}
  labels:
    {{- include "snapshot-validation-webhook.labels" . | nindent 4 }}
  {{- if .Values.tls.certManagerIssuerRef }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "snapshot-validation-webhook.fullname" . }}
  {{- end }}
webhooks:
  - name: {{ include "snapshot-validation-webhook.name" . }}.csi.kubernetes.io
    rules:
      - apiGroups:
        - snapshot.storage.k8s.io
        apiVersions:
        - v1
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - volumesnapshots
        - volumesnapshotcontents
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "snapshot-validation-webhook.fullname" . }}
        path: "/volumesnapshot"
      {{- if not .Values.tls.certManagerIssuerRef }}
      {{- $secret := lookup "v1" "Secret" .Release.Namespace (include "snapshot-validation-webhook.certifcateName" .) }}
      {{- if $secret }}
      caBundle: {{ get $secret.data "ca.crt" }}
      {{- else }}
      caBundle: ""
      {{- end }}
      {{- end }}
    admissionReviewVersions:
    - v1
    - v1beta1
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
